### ISSUE TITLE
FatalProcessOutOfMemory

### ISSUE THREAD

**Issue by okwme** [keppel/lotion#116]
Whenever i leave my lotion app to run on a bare-bone digital ocean server it crashes after a few days with `FatalProcessOutOfMemory`

here's my actual error logs:

```
0|app      | FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory
0|app      |  1: node::Abort() [node /home/goodcorp_server/app.js]
0|app      |  2: 0x8d04bc [node /home/goodcorp_server/app.js]
0|app      |  3: v8::Utils::ReportOOMFailure(char const*, bool) [node /home/goodcorp_server/app.js]
0|app      |  4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node /home/goodcorp_server/app.js]
0|app      |  5: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node /home/goodcorp_server/app.js]
0|app      |  6: v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node /home/goodcorp_server/app.js]
0|app      |  7: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node /home/goodcorp_server/app.js]
0|app      |  8: v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node /home/goodcorp_server/app.js]
0|app      |  9: 0x3b1ad8042fd
0|app      | Error: read ECONNRESET
0|app      |     at TCP.onread (net.js:602:25)
0|app      | /home/goodcorp_server/node_modules/supercop.js/lib.js:97
0|app      |       throw ex;
0|app      |       ^
0|app      |
0|app      | Error: read ECONNRESET
0|app      |     at TCP.onread (net.js:602:25)
```

i thought i remembered something in a lotion.js tutorial about configuring swapfiles on digitalocean, was there ever something like that? is this a memory leak? i'm using mappum/coins and keppel/shea, the repo is here: https://github.com/okwme/goodcorp_server

any tips for keeping my chain alive?

**Comment by keppel** [comment]
I think shea used to cause this, I think it was a memory leak. Closing this!
