### ISSUE TITLE
Websocket disconnected

### ISSUE THREAD

**Issue by rllola** [keppel/lotion#142]
Even with the simplest example I have this error.

```
/home/lola/Workspace/Pillar/basic-coin/node_modules/supercop.js/lib.js:97
      throw ex;
      ^

Error: websocket disconnected
    at Pumpify.<anonymous> (/home/lola/Workspace/Pillar/basic-coin/node_modules/tendermint/lib/rpc.js:92:37)
    at emitNone (events.js:111:20)
    at Pumpify.emit (events.js:208:7)
    at Pumpify.Duplexify._destroy (/home/lola/Workspace/Pillar/basic-coin/node_modules/duplexify/index.js:199:8)
    at /home/lola/Workspace/Pillar/basic-coin/node_modules/duplexify/index.js:182:10
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Not sure what is happening

I just have this simple client:
```
let lotion = require('lotion')

let client = lotion.connect('9079018273a21f3ffbe1f58b7fd9713a7a29102f95d045740368e7f931edeb89')
  .then(async function (result) {

    console.log(result)
  })
```

**Comment by keppel** [comment]
hi Lola!

are you running the same version of lotion on your client and app?

**Comment by rllola** [comment]
Yes, I am using the same.
Here the small example I am trying to run : https://github.com/rllola/basic-coin

**Comment by keppel** [comment]
I got the same issue when I ran your example, sorry about that! not sure what's causing that.

if you update to lotion@0.1.19 this should be fixed (make sure to `rm -rf ~/.lotion` or run the app with `devMode: true` to clear the blockchain data).

**Comment by rllola** [comment]
`lotion@0.1.19` is not working for me. I have an other kind of error so it is progress.

```
error starting tendermint node:
Error: Timed out while waiting
    at /home/lola/Workspace/Pillar/basic-coin/node_modules/tendermint-node/src/index.js:119:15
    at <anonymous>
```

**Comment by rllola** [comment]
`0.1.12` is working for me tho.
