### ISSUE TITLE
Mac Installation Not Working

### ISSUE THREAD

**Issue by niharrs** [keppel/lotion#157]
**Running the following comand:**
`$ npm install lotion --save`

**Getting the following output:**
```
/Users/niharikasingh/Desktop/Playground/blockchainlotion/node_modules/tendermint-node/bin/download.js:92
    copyFileSync(binPath, cacheBinPath)
    ^

TypeError: copyFileSync is not a function
    at WriteStream.file.on (/Users/niharikasingh/Desktop/Playground/blockchainlotion/node_modules/tendermint-node/bin/download.js:92:5)
    at emitNone (events.js:110:20)
    at WriteStream.emit (events.js:207:7)
    at finishMaybe (_stream_writable.js:587:14)
    at afterWrite (_stream_writable.js:439:3)
    at onwrite (_stream_writable.js:429:7)
    at fs.js:2133:5
    at FSReqWrap.wrapper [as oncomplete] (fs.js:690:5)
```

**Comment by keppel** [comment]
hey @niharrs!

looks like you're on an old version of node, try updating (I recommend [nvm](https://github.com/creationix/nvm))
