### ISSUE TITLE
JSON parsing error 

### ISSUE THREAD

**Issue by LowkeyCoding** [keppel/lotion#163]
node version: 10.14.2
npm version: 6.4.1
lotion version: 1.18.0
ubuntu version: 18.04 LTS
Used the lotion version i saw in a tutorial. When i decided to update it the .listen function don't work at all.
SyntaxError: Unexpected token - in JSON at position 0
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (/home/lowkey/Documents/Development/Dnet/node_modules/body-parser/lib/types/json.js:158:10)
    at parse (/home/lowkey/Documents/Development/Dnet/node_modules/body-parser/lib/types/json.js:83:15)
    at /home/lowkey/Documents/Development/Dnet/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/home/lowkey/Documents/Development/Dnet/node_modules/raw-body/index.js:224:16)
    at done (/home/lowkey/Documents/Development/Dnet/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/lowkey/Documents/Development/Dnet/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
_________________________
node version: 10.14.2
npm version: 6.4.1
lotion version: 0.3.0
ubuntu version: 18.04 LTS

TypeError: app.listen is not a function
    at Object.<anonymous> (/home/lowkey/Documents/Development/Dnet/testchain.js:15:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by LowkeyCoding** [comment]
script: 
let lotion = require('lotion')

let app = lotion({
  initialState: {
    count: 0
  }
})

app.use(function(state, tx) {
  if (state.count === tx.nonce) {
    state.count++
  }
})

app.listen(3000)

**Comment by mappum** [comment]
Not sure about the first error, but `app.listen(PORT)` was replaced with `app.start()` in a recent version.

**Comment by LowkeyCoding** [comment]
cleaning the networks folder using " rm -rf ~/.lotion/networks/*" seems to fix the issue
