### ISSUE TITLE
UnhandledPromiseRejectionWarning (Node 8.10.0)

### ISSUE THREAD

**Issue by Abstrct** [keppel/lotion#189]
I tried to build the example application from the readme & lotionjs.com but I keep hitting this same issue. The application appears to keep running despite the errors/warnings, but the GCI never shows up. 

```
(node:31810) Warning: N-API is an experimental feature and could change at any time.
(node:31810) UnhandledPromiseRejectionWarning: Error: spawn EACCES
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:502:9)
    at module.exports (/home/parallels/node_modules/execa/index.js:204:26)
    at exec (/home/parallels/node_modules/tendermint-node/src/index.js:21:40)
    at Object.init (/home/parallels/node_modules/tendermint-node/src/index.js:157:19)
    at Object.<anonymous> (/home/parallels/node_modules/lotion/dist/tendermint.js:61:53)
    at step (/home/parallels/node_modules/lotion/dist/tendermint.js:32:23)
    at Object.next (/home/parallels/node_modules/lotion/dist/tendermint.js:13:53)
    at /home/parallels/node_modules/lotion/dist/tendermint.js:7:71
(node:31810) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:31810) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:31810) UnhandledPromiseRejectionWarning: Error: spawn EACCES
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:502:9)
    at module.exports (/home/parallels/node_modules/execa/index.js:204:26)
    at exec (/home/parallels/node_modules/tendermint-node/src/index.js:21:40)
    at Object.init (/home/parallels/node_modules/tendermint-node/src/index.js:157:19)
    at Object.<anonymous> (/home/parallels/node_modules/lotion/dist/tendermint.js:61:53)
    at step (/home/parallels/node_modules/lotion/dist/tendermint.js:32:23)
    at Object.next (/home/parallels/node_modules/lotion/dist/tendermint.js:13:53)
    at /home/parallels/node_modules/lotion/dist/tendermint.js:7:71
(node:31810) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
```

The code isn't anything special but, if it helps:

```

let lotion = require('lotion');

let app = lotion({
        initialState: {
                count: 0,
        }
})

function transactionHandler(state, transaction) {
        if (state.count === transaction.nonce) {
                state.count++;
        }
}

app.use(transactionHandler);

app.start().then(function(appInfo) { console.log(appInfo.GCI)});

```

Node 8.10.0
lotion 0.4.26

**Comment by Abstrct** [comment]
FWIW, I used a completely different computer (MacOS, node v10.15.0) and lotion is working great.
