### ISSUE TITLE
Error when launching server

### ISSUE THREAD

**Issue by canaryGrapher** [keppel/lotion#197]
Whenever I try to run the node server, I get the same issue.  Any help?

This is my error: 

```
c*********************************************09 (GCI)
(node:15748) UnhandledPromiseRejectionWarning: Error: invalid wire type 7 at offset 95
    at BufferReader.Reader.skipType (C:\Users\Yash\Documents\GitHub\first-blockchain-app\node_modules\protobufjs\src\reader.js:377:19)
    at Function.decode (C:\Users\Yash\Documents\GitHub\first-blockchain-app\node_modules\abci\types.js:8722:28)

C:\Users\Yash\Documents\GitHub\first-blockchain-app>node server.js
cf8e0b466699aba798b3e0b12b54416edabeea99c659e8f52e6e3364c2d48609
(node:14908) UnhandledPromiseRejectionWarning: RangeError: index out of range: 139 + 79082468 > 365
    at indexOutOfRange (C:\Users\Yash\Documents\GitHub\first-blockchain-app\node_modules\protobufjs\src\reader.js:13:12)
    at BufferReader.read_bytes [as bytes] (C:\Users\Yash\Documents\GitHub\first-blockchain-app\node_modules\protobufjs\src\reader.js:310:15)
    at Function.decode (C:\Users\Yash\Documents\GitHub\first-blockchain-app\node_modules\abci\types.js:8244:57)
    at Function.decode (C:\Users\Yash\Documents\GitHub\first-blockchain-app\node_modules\abci\types.js:2114:56)
    at Function.decode (C:\Users\Yash\Documents\GitHub\first-blockchain-app\node_modules\abci\types.js:256:71)
    at Connection.maybeReadNextMessage (C:\Users\Yash\Documents\GitHub\first-blockchain-app\node_modules\abci\src\connection.js:55:27)      
    at Connection.onData (C:\Users\Yash\Documents\GitHub\first-blockchain-app\node_modules\abci\src\connection.js:32:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
(node:14908) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without 
a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:14908) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by keppel** [comment]
If you update to v0.4.27, this issue should be fixed -- sorry for the inconvenience!

**Comment by canaryGrapher** [comment]
Thanks, it's working now
