### ISSUE TITLE
TypeError: app.listen is not a function

### ISSUE THREAD

**Issue by cayden** [keppel/lotion#200]
When executing "node app.js ”，The following error occurred

TypeError: app.listen is not a function
    at Object.<anonymous> (/root/goApps/src/github.com/tendermint/counter/app.js:17:5)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by helmiatwork** [comment]
@cayden repost issue [#167](https://github.com/nomic-io/lotion/issues/167)

**Comment by cayden** [comment]
@helmiatwork thank you!
