### ISSUE TITLE
Trouble installing on m1

### ISSUE THREAD

**Issue by johannbotha** [keppel/lotion#206]
I'm having trouble installing on an apple m1 chip. Does anyone else have this?
`node v16.10.0`
`npm  v7.24.0`

This is the resulting error from `npm install lotion`
```
1095 verbose argv "~/.nvm/versions/node/v16.10.0/bin/node" "~/.nvm/versions/node/v16.10.0/bin/npm" "install" "lotion"
1096 verbose node v16.10.0
1097 verbose npm  v7.24.0
1098 error code 1
1099 error path ~/Code/shitcoin/node_modules/tendermint-node
1100 error command failed
1101 error command sh -c node ./bin/download.js
1102 error downloading tendermint v0.31.5
1103 error ~/Code/shitcoin/node_modules/axios/lib/core/createError.js:16
1103 error   var error = new Error(message);
1103 error               ^
1103 error
1103 error Error: Request failed with status code 404
1103 error     at createError (~/Code/shitcoin/node_modules/axios/lib/core/createError.js:16:15)
1103 error     at settle (~/Code/shitcoin/node_modules/axios/lib/core/settle.js:17:12)
1103 error     at RedirectableRequest.handleResponse (~/Code/shitcoin/node_modules/axios/lib/adapters/http.js:210:9)
1103 error     at RedirectableRequest.emit (node:events:390:28)
1103 error     at RedirectableRequest._processResponse (~/Code/shitcoin/node_modules/follow-redirects/index.js:269:10)
1103 error     at ClientRequest.RedirectableRequest._onNativeResponse (~/Code/shitcoin/node_modules/follow-redirects/index.js:50:10)
1103 error     at Object.onceWrapper (node:events:510:26)
1103 error     at ClientRequest.emit (node:events:390:28)
```

**Comment by ppedziwiatr** [comment]
that's probably due to the fact that the tendermint-node package is trying to download the binary of tendermint for arm64 architecture for version 0.31.5 - this version is not available for darwin/arm64

Anyway, since the version of tendermint is so old (0.31.5 - there aren't even docs available for this version), I think it is no longer usable.

**Comment by ppedziwiatr** [comment]
If you want to make the lotion to work, you can manually download the binary and put it into the `node-modules/tendermint-node/bin`. The latest version that is compatible with lotion is https://github.com/tendermint/tendermint/releases/tag/v0.32.14 (darwin/amd64 - it will run in Rosetta mode).

Unfortunately 0.33 does not work, it gives the same error as described here: https://github.com/nomic-io/tendermint-node/issues/15 (as `tendermint-node` `5.2.0` makes tendermint upgrade to `0.33`).
